[[IgnoredVulns]]
id = "GHSA-qh8g-58pp-2wxh"
reason = "Not applicable in a wiremock lambda implementation"


[[IgnoredVulns]]
id = "GHSA-pq2g-wx69-c263"
ignoreUntil = 2025-04-01 
reason = "Awaiting release of fix from transient dependency"